### ISSUE TITLE
[Bug]: Conflict with CraftTweaker, can't enter the game

### ISSUE THREAD

**Issue by LMaxRouterCN** [nonamecrackers2/simple-clouds#100]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.12

### Describe the Bug

Crashes and throws a report when starting the game.

### Steps to Reproduce

starting the game.

### Crash Reports/Logs

[错误报告-2024-12-21_6.06.27.zip](https://github.com/user-attachments/files/18215924/-2024-12-21_6.06.27.zip)

### Mod List

There are a lot of other mods out there, but I don't think this has anything to do with them. If you need a list of mods, you can find it in the file I uploaded.

**Comment by pinkygrocket** [comment]
run the game with only crafttweaker and simple clouds installed; you have a lot of other mods installed and sinytra connector is present, so it's probably not a conflict with crafttweaker.

**Comment by nonamecrackers2** [comment]
Looks like you need createtweaker? Not sure but this doesn’t seem Simple Clouds related. Simple Clouds is crashing because another mod crashed. This will be fixed in the next release

**Comment by LMaxRouterCN** [comment]
Okay, I get it.
