### ISSUE TITLE
[Suggestion]: Make the mod Free and Open Source

### ISSUE THREAD

**Issue by souldbminerr** [nonamecrackers2/simple-clouds#101]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Free and open source mods are nice for everyone, allows porting and more usage

**Comment by TSEG6** [comment]
You do realize this is already open source right?

**Comment by souldbminerr** [comment]
It isn't FREE and open source.

**Comment by DrMalpracticewastaken** [comment]
> It isn't FREE and open source.

its LITERALLY FREE. You can go and download the mod without spending money here: https://www.curseforge.com/minecraft/mc-mods/simple-clouds
what are you even here for bruh

**Comment by nonamecrackers2** [comment]
The mod is free for anyone to download and the license will not be changed. Is there something you would like to see that makes you want this mod portable?

**Comment by souldbminerr** [comment]
Mainly the competition clause, as the problem with it is that QoL forks are not allowed
