### ISSUE TITLE
[Bug]: Rendering crash when storm is happening (?)

### ISSUE THREAD

**Issue by VelvetSorcerer2** [nonamecrackers2/simple-clouds#104]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.21.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Graphics Card

NVIDIA Geforce GTX 1660

### Describe the Bug

I can run Minecraft until I spawn in the world, where it'll run for a total of a few seconds before everything freezes and crashes like 30 seconds later. I was able to open the world perfectly fine and exist in Minecraft's menus without issue, but for some reason every time it will freeze then crash. No clue what it's caused by other than a "fatal rendering" issue.

### Steps to Reproduce

1. Open Minecraft
2. Join a singleplayer world
3. Freezes and crashes a few seconds later

### Crash Reports/Logs

[crash-2024-12-26_16.57.43-client.txt](https://github.com/user-attachments/files/18256060/crash-2024-12-26_16.57.43-client.txt)
[latest.log](https://github.com/user-attachments/files/18256065/latest.log)

### Mod List

.connector (disabled)
3d-Skin-Layers 
Apothic Attributes 
AppleSkin 
Aquaculture 2 
Aquaculture Delight 
Architectury 
AttributeFix 
Balm 
Better Advancements 
Better Combat 
Better tom's create storage 1.1 
BetterF3 
Blur (Forge) 
Botarium 
Byzantine 
Caelus API 
Carry On 
Cave Dust 
Charm of Undying 
Chat Heads 
ChoiceTheorem's Overhauled Village 
Chunky 
Cloth Config v10 API 
Clumps 
Collector's Reap 
Comforts 
Common Networking 
Compatibility addon for MineColonies 
CoroUtil 
Corpse 
CosmeticArmorReworked 
Create 
Create : Encased 
Create Big Cannons 
Create Cafe 
Create Chunkloading 
Create Compact Exp 
Create Compressed 
Create Confectionery 
Create Crafts & Additions 
Create Deco 
Create Diesel Generators 
Create Enchantment Industry 
Create Jetpack 
Create Liquid Fuel 
Create Recycling 
Create Sabers 
Create Slice & Dice 
Create Stuff & Additions 
Create Teleporters 
Create: Bells & Whistles 
Create: Central Kitchen 
Create: Connected 
Create: Copycats+ 
Create: Design n' Decor 
Create: Dreams & Desires 
Create: Dynamic Village 
Create: Easy Structures 
Create: Factory 
Create: Framed 
Create: Interiors 
Create: Love and War 
Create: New Age 
Create: Steam 'n' Rails 
Create: The Factory Must Grow 
Create_Better_Villagers 
Cupboard utilities 
Curios API 
Decorative Blocks 
Default-Dark-Mode-1.20-2023.7.0 
Distant Horizons 
Do a Barrel Roll 
Domum Ornamentum 
Dungeons and Taverns 
EMI 
EMI Loot 
EMI Trades 
Easy Magic 
Easy Villagers 
Eating Animation 
EclecticTrove-1.20.1-1.3.0 
Effective (disabled)
Elytra Slot 
Embeddium 
Embeddium Extra 
Embeddium++ 
Ender's Delight 
Entity Model Features 
Entity Texture Features 
Essential Mod 
Explorer's Compass 
Explosive Enhancement 
Extended Cogwheels 
FA+All_Extensions-v1.4 
Falling Leaves 
Farmer's Delight 
Farmer's Respite 
Fast Better Grass 
Fast Leaf Decay 
Ferrite Core 
Flan's Mod 
Forgified Fabric API 
FreshAnimations_v1.9.2 
Fusion 
Fzzy Config 
Gateways To Eternity 
GeckoLib 4 
GeckoLibIrisCompat 
GlitchCore 
Handcrafted 
Icarus 
Iceberg 
Jade 
Jade Addons 
JadeColonies 
Just Enough Items 
Legendary Tooltips 
Let's Do addon for MineColonies 
Lithosphere 
Lithostitched 
Lootr 
Lopy-Create-Sophisticated-Backpacks 
LowOnFire_1.20.1 
Macaw's Doors 
Macaw's Furniture 
Macaw's Roofs 
Macaw's Windows 
MineColonies 
Miner's Delight 
MmmMmmMmmmmm 
Moonlight Library 
Mouse Tweaks 
Multi-Piston 
Nature's Compass 
Nether's Delight 
No Chat Reports 
Noisium 
NotEnoughAnimations 
Oculus 
Oculus Flywheel Compat 
Overflowing Bars 
Placebo 
Player Animator 
Polymorph 
Prism 
Puzzles Lib 
Resourceful Lib 
Resourcefulconfig 
RunicGrimoireDisabler 
SecurityCraft 
Serene Seasons 
Shiny Trims v6 (Optifine) 
ShulkerBoxTooltip 
Simple Clouds 
Simple Voice Chat 
Simply Swords 
Sinytra Connector 
Smoothchunk mod 
Sodium Extras 
Sodium Options API 
Sophisticated Backpacks 
Sophisticated Core 
Sophisticated Storage 
Sound Physics Remastered 
Storage Drawers 
Structure Essentials mod 
Structurize 
Supplementaries 
Terralith 
Tom's Simple Storage Mod 
TownTalk 
Trading Post 
Tweaks addon for MineColonies 
UI Library Mod 
Visual Workbench 
Visuality: Reforged 
Waystones 
What Are They Up To 
Xaero's Minimap 
Xaero's World Map 
YUNG's API 
YUNG's Better Desert Temples 
YUNG's Better Jungle Temples 
YUNG's Better Ocean Monuments 
YUNG's Better Witch Huts 
[1.4.1] Enhanced Boss Bars 
[Let's Do] API 
[Let's Do] Bakery 
[Let's Do] Beachparty 
[Let's Do] Brewery 
[Let's Do] Farm & Charm 
[Let's Do] Furniture 
[Let's Do] HerbalBrews 
[Let's Do] Vinery 
betterchunkloading mod 
create: things and misc 
gml-4.0.9-all 
kotlinforforge-4.11.0-all 
stylecolonies mod 
underground_village 
waystones_1.20

**Comment by VelvetSorcerer2** [comment]
Also want to clarify: this exact same setup was working just fine the other day, I was testing other mods the other day and nothing went wrong

**Comment by nonamecrackers2** [comment]
Known issue, fixing #78 should fix this one
