### ISSUE TITLE
[Suggestion]: compatibility and weather features.

### ISSUE THREAD

**Issue by CobaltGlacier** [nonamecrackers2/simple-clouds#105]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

There should be Compatibility with Serene seasons, skyfall meteorites, and provided hurricanes and tornadoes aren't added to the mod either in this mod or to a separate mod, compat with weather 2.

I feel like tornadoes, hail, sandstorms, dust storms, hurricanes/tropical storms, and fog would make really good additions to the mod as well

**Comment by nonamecrackers2** [comment]
Please only one feature per issue
