### ISSUE TITLE
[Bug]: Crashing when opening the game [Apple Mac related]

### ISSUE THREAD

**Issue by SackUhTaters** [nonamecrackers2/simple-clouds#14]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.7

### Graphics Card

Apple M2

### Describe the Bug

A bug happened!
Whenever i open the game it crashes before the title screen shows.

### Steps to Reproduce

1. Go to Minecraft launcher
2. Click on Play
3. Wait
4. Game crashes

### Crash Reports/Logs

[crash-2024-10-16_22.00.23-client.txt](https://github.com/user-attachments/files/17404984/crash-2024-10-16_22.00.23-client.txt)

### Mod List

Simple Clouds

**Comment by rubiidev18alt** [comment]
are you using fold craft/pojav launcher?

**Comment by SackUhTaters** [comment]
> are you using fold craft/pojav launcher?

nope just the normal minecraft launcher

**Comment by nonamecrackers2** [comment]
Might be a potential M2 mac issue, but will have to investigate further

**Comment by thelegitdolt** [comment]
also happens with me (I have a M1 Mac)

**Comment by cramsrab** [comment]
happens for me as well! My mac is an m2

**Comment by VIDQUC** [comment]
The same thing is happening to me, but im on windows ten, not sure whats going on there.

**Comment by nonamecrackers2** [comment]
Yeah it's a very strange bug, I'm not really sure what is going on here. This may not be necessarily mac related anymore, but it seems to be related to #3? Will be investigating further

**Comment by lynxjr3** [comment]
Yeah but i am using a hackintoshed pc so mine is a intel gpu, and yes its crashing.

Edit: Also you can hackintosh a pc laying down if you want so you dont have to give your kidney. Or you can use a Virtual Machine.

**Comment by nonamecrackers2** [comment]
Looks like Macs only support OpenGL 4.1: `` Apple M2 GL version 4.1 Metal - 88.1, Apple
``. The game crashes here though without this being obvious due to a bug in the mod, but in newer versions it'll be more obvious that OpenGL is out of date and that Simple Clouds cannot launch.

I don't think I will be able to get Macs to work since the mod needs compute shaders which are at least OpenGL 4.2+ (4.2 with extensions), so Macs will unfortunately be incompatible with Simple Clouds (at least those with M1 and M2 chips which are known to be incompatible)

**Comment by thelegitdolt** [comment]
it's cloudover

**Comment by 9182736450typist** [comment]
Could I run Asahi LINUX on an M series mac (since that allows opengl 4.6 compatibility) to get the mod to work.
PS: I am currently using an intel mac and it doesn't work.

**Comment by nonamecrackers2** [comment]
Possibly though I do not know

**Comment by LarveyOfficial** [comment]
This seems to just be an issue with macOS in general. Tested on a 2019 Mac Pro (Intel CPU) and issue also occurs.

**Comment by jacobennis** [comment]
I Have a 2015 Imac 5k, Intel I5 and Radeon R9 2gb. I have 32 GB of ram, and my computer supports up to open gl 4.5 and it still crashes. no idea why.
