### ISSUE TITLE
[Suggestion]: 4 suggestions! check thread :)

### ISSUE THREAD

**Issue by JustN00ne** [nonamecrackers2/simple-clouds#22]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

# Suggestion 1 - Fabric support
Hello Crackers! I know many users may have asked you this, BUT i will ask you once more for another version, is 1.19.2 support possible, if not lmk. But i really would love to see this mod on my server but it is 1.19.2 Fabric. It is a realistic creative server so it would be really a nice touch. 

# Suggestion 2 - Overcast. 
Self explanatory, but still a nice addition to make big cloud "carpets" that stretch over 5000's of blocks.

# Suggestion 3 - Perhaps different cloud colors and shader integration
So, for example at night, all clouds will be black, and if there is the golden hour, the clouds will be orange. Also possible shader integration so the clouds will have shader support (lmk if possible)

# Suggestion 4 - Light pollution
If there are over 10 light sources that are brighter than 12 in 1 chunk, then the clouds above will be yellowish at night, which would be a perfect integration for suggestion 3! It also can be useful for finding your base too if you are playing with this mod on survival mode :)

So yea thats all! Thanks so much for this amazing mod :heart

**Comment by ShadowmeC3** [comment]
Well for one you broke 2 rules, one being only one suggestion per thread, and 2 you are not allowed to suggest different versions or different mod loaders. So uhh ya :3

**Comment by JustN00ne** [comment]
oh, imma fix it then

**Comment by JustN00ne** [comment]
also it wasnt mentioned

**Comment by JustN00ne** [comment]
Broke a few rules, closed due to suggestion split
