### ISSUE TITLE
[Bug]: Cloud renderer fails when a different mod fails

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/simple-clouds#3]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.1.3

### Graphics Card

RTX 3606 Ti

### Describe the Bug

Loot journal 4.0.2 requires a higher forge version then what I used. When I launched the game, it crashed multiple times telling me "renderer not initialized." I disabled simple clouds to figure out the actual issue. One mod failing when a different mod fails is something that other mods like immersiveFx, and other mods seem to run into. Not a huge issue but can be annoying if you're not aware ahead of time.

### Steps to Reproduce

1. On forge 47.1.3, add loot journal 4.0.2 and simple clouds latest
2. Launch game
3. See error

### Crash Reports/Logs

[crash-2024-10-15_15.02.35-client.txt](https://github.com/user-attachments/files/17383645/crash-2024-10-15_15.02.35-client.txt)

### Mod List

Loot journal (forge) 4.0.2

**Comment by TSEG6** [comment]
![image](https://github.com/user-attachments/assets/2e306843-fe5b-4bfe-9992-cdf8b25c93a6)

nice gpu lol

**Comment by GrandmaPork** [comment]
lmao 3060 i wasnt paying attention

**Comment by nonamecrackers2** [comment]
Could you send your latest.log?

**Comment by GrandmaPork** [comment]
i don't have the crash available in my latest log, but i can recreate the crash later if you're unable to

**Comment by nonamecrackers2** [comment]
That's okay, this should be fixed in the next major release
