### ISSUE TITLE
[Bug]: Crash on Start: Incompatibility with other mods.

### ISSUE THREAD

**Issue by Gavin456b** [nonamecrackers2/simple-clouds#37]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.11

### Graphics Card

Nvidia GeForce RTX 3080

### Describe the Bug

Crash on launch in custom modpack. Not sure exactly what the incompatibility is but the crash log seems to indicate something. And the mod works on it's own.

### Steps to Reproduce

1. Launch game
2. Crashes on Forge loading screen

### Crash Reports/Logs

[crash-2024-10-20_19.31.54-client.txt](https://github.com/user-attachments/files/17452657/crash-2024-10-20_19.31.54-client.txt)

### Mod List

See crash log

**Comment by nonamecrackers2** [comment]
Looks to be the same as #3, fixing that should fix this
