### ISSUE TITLE
[Suggestion]: A new setting in the CWSM World options 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/simple-clouds#41]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A option where you can make the skulls not break any blocks but only set things on fire ( would work really great with the " Burnt " Mod )
![image](https://github.com/user-attachments/assets/93a5bfe2-c773-4b70-830d-dc4fbc3d0aa1)
![image](https://github.com/user-attachments/assets/2dd1d296-22da-49f5-8225-d6c99e3166e6)
The photos give a example of what the wither storm skulls would do if they only set things on fire instead of breaking blocks

**Comment by Thefuzz1234555** [comment]
You opened this in the Simple Clouds github

**Comment by Infinitekaosv3** [comment]
> You opened this in the Simple Clouds github

Oh god
