### ISSUE TITLE
[Bug]: Game crashes on start up, windows 10

### ISSUE THREAD

**Issue by VIDQUC** [nonamecrackers2/simple-clouds#45]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.11

### Graphics Card

Nividia GTX 1660 super

### Drivers Version

555.85

### Describe the Bug

So i have downloaded the mod, i put it into the folder and load up forge and just before reaching the title screen, the game crashes.
Im not sure why it does this ive heard people have been having this issue before but not on windows 10. I have reinstalled forge and it still crashes, i have removed everything but the mod from the mod folder and it still dont work.

### Steps to Reproduce

1. load up the launcher
2. use forge version
3. click play
4. wait for the game to load
5. then it crashes

### Crash Reports/Logs

https://github.com/user-attachments/files/17500270/crash-2024-10-24_13.32.00-client.txt

### Mod List

i had better brightness slider and optifine as my 2 mods

**Comment by VIDQUC** [comment]
i didnt research enough, your not supposed to have optifine LOL

**Comment by nonamecrackers2** [comment]
Yeah OptiFine is not compatible unfortunately

**Comment by VIDQUC** [comment]
yeah all good great mod btw
