### ISSUE TITLE
[Bug]: amd

### ISSUE THREAD

**Issue by spooky1046** [nonamecrackers2/simple-clouds#49]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Graphics Card

AMD Radeon RX 6600 XT

### Drivers Version

idk

### Describe the Bug

i think the mod is incompatible with amd cards

### Crash Reports/Logs

none

### Screenhots

![image](https://github.com/user-attachments/assets/0ab36fb0-4099-4cb8-a0ce-2ff189e8817f)

### Mod List

![Posnetek zaslona (58)](https://github.com/user-attachments/assets/7295dc58-ac75-46b2-b707-798f2eb59ea5)

**Comment by DredFul2** [comment]
im almost having the same problem

**Comment by Luviam** [comment]
I Beg, please confirm it still happens with just Simple Clouds.

**Comment by KorbynTalks** [comment]
thats weird. I am using a rx 560 and I dont have that problem

**Comment by redshadow3** [comment]
Same as issue  #30.

**Comment by bmartin127** [comment]
I have an amd card and I do not have this issue

**Comment by nonamecrackers2** [comment]
#30
