### ISSUE TITLE
[Bug]: Distant Horizon terrain hidden behind far away clouds.  

### ISSUE THREAD

**Issue by Recorpse** [nonamecrackers2/simple-clouds#50]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Graphics Card

GTX 1080

### Describe the Bug

When using this mod with Distant Horizons as well as using shaders with Oculus the clouds show Infront of distant horizon terrain as you can see here.
![image_2024-10-25_222510209](https://github.com/user-attachments/assets/6a4d57a8-4566-4ae7-9bf1-bbdb3f082a94)

To reproduce this problem you simply need Oculus 1.7.0, Embeddium 0.3.31, and Distant Horizon 2.1.0, as well as simple clouds of course. When you look into the distance, things like mountains, trees, and structures that aren't even that tall will be hidden by clouds that are very clearly way off in the distance compared to the terrain and yet it still is showing Infront of the terrain

### Steps to Reproduce

1. Oculus 1.7.0
2. Embeddium 0.3.31
3. Distant Horizon 2.1.0
4. look at DH lod of a distant mountain or structure and you will see clouds hiding the distant horizon terrain 
![Untitled](https://github.com/user-attachments/assets/d22e5aed-2ff2-4a2d-a749-fd69d2bca9d8)

### Crash Reports/Logs

N/A

### Mod List

Oculus 1.7.0
Embeddium 0.3.31
Distant Horizon 2.1.0
Simple Clouds 0.6.3

**Comment by nonamecrackers2** [comment]
Going to close this in favor of #4, fixing that should fix this once compat is added
