### ISSUE TITLE
[Suggestion]: Clouds have a color change when near the wither storm

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/simple-clouds#53]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The simple clouds could become purple when a wither storm (phase 4/5+) is nearby, with the clouds closest to the wither storm being a pinkish purple and slowly it would fade to dark purple to the default as the clouds get further away. 

It would make the wither storm very ominous if it's in/near storms and clouds

**Comment by nonamecrackers2** [comment]
This is already a thing for the higher phases, but since phase 4/5 don't darken the sky I feel like this shouldn't happen. It might look out of place (even if it is local to around the Wither Storm).

**Comment by SSgamingYT** [comment]
> This is already a thing for the higher phases, but since phase 4/5 don't darken the sky I feel like this shouldn't happen. It might look out of place (even if it is local to around the Wither Storm).

I meant the distant clouds (near the wither storm, but not near the player) have a purple hue, I'm already aware that there is an effect when the storm is close
