### ISSUE TITLE
[Compatibility]: Distant Horizons rendering over Simple Clouds when above the Clouds.

### ISSUE THREAD

**Issue by MultiCatRain** [nonamecrackers2/simple-clouds#63]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Graphics Card

x

### Drivers Version

x

### Describe the Bug

This is just a simple compatibility issue. As of right now, if you are above the clouds, the distant horizons LOD with render after the Simple Cloud rendering. This is a good thing, because if you are below the clouds (Which is basically always) the clouds wont render over tall surfaces and stuff. However, if you are above the clouds, the DH Lod appears on top of Simple Clouds. I was just wondering if it would be possible to make it so DH renders before Simple Clouds or something if you are looking at the top face of the cloud layer or something.

### Steps to Reproduce

x

### Crash Reports/Logs

x

### Screenhots

![2024-10-27_15 34 10](https://github.com/user-attachments/assets/9ebc1225-c5fa-47fe-bff3-834d37baba37)
 

### Mod List

SimpleClouds
Distant Horizons
Weather2
CoroUtil

**Comment by nonamecrackers2** [comment]
Going to close this in favor of #4. DH is currently not supported by compatibility will be looked into
