### ISSUE TITLE
[Bug]: Brother keeps crashing whenever it rains

### ISSUE THREAD

**Issue by LordSeabass** [nonamecrackers2/simple-clouds#66]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Graphics Card

AMD 7700XT

### Drivers Version

24.10.1

### Describe the Bug

Crash when thunderstorms or rain storms happen

### Steps to Reproduce

Wait for a storm to approach and when it rains it crashes.

### Crash Reports/Logs

[Crash Log](https://pastebin.com/qiF7C8W6)
[Log](https://pastebin.com/viK2Pb9T)

### Mod List

Another Furniture (by Starfish_Studios)
Enchantment Descriptions (by DarkhaxDev)
Simple Clouds (by nonamecrackers2)
Client Crafting (by someaddon)
Quark (by Vazkii)
Icon Xaero's (by godkyo98)
Tax' Village Architect (by Taknax)
AmbientSounds 6 (by CreativeMD)
SuperMartijn642's Config Lib (by SuperMartijn642)
Embeddium (by FiniteReality)
Wakes (by Goby56)
OctoLib (by SSKirillSS)
Zeta (by Vazkii)
Balm (Forge Edition) (by BlayTheNinth)
Alex's Mobs (by sbom_xela)
Fzzy Config (by fzzyhmstrs)
Woodworks (by TeamAbnormals)
Rats (by sbom_xela)
Model Gap Fix (by MehVahdJukaar)
Dungeons and Taverns (by Nova_Wostra)
Backpacked Recipe Fix (by chorb)
Fancy Crops (by bebebea_loste)
Geophilic Reforged – Biome Additions (by bebebea_loste)
Villager Names (by Serilum)
Moonlight Lib (by MehVahdJukaar)
Farmer's Respite (by lumpazl)
Combat Roll [Fabric & Forge] (by daedelus_dev)
Tectonic (by Apollo)
Hopo Better Ruined Portals (Fabric/Forge/NeoForge) (by hoponopono)
Amplified Nether (by Starmute)
YUNG's Cave Biomes (Forge) (by YUNGNICKYOUNG)
Better Archeology (by Pandarix)
ImmediatelyFast (by RaphiMC)
Nicer Skies (by ztereohype)
Paxi (Forge) (by YUNGNICKYOUNG)
[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)
SeasonHUD (by IanAnderson)
Not Enough Animations (by tr7zw)
Yeetus Experimentus (by Sunekaer)
Formations Nether (by SuperMartijn642)
M.R.U (by IMB11)
FerriteCore ((Neo)Forge) (by malte0811)
Falling Leaves (NeoForge/Forge) (by Cheaterpaul)
ModernFix (by embeddedt)
Inventory Essentials (by BlayTheNinth)
Easy Anvils [Forge & Fabric] (by Fuzs)
Noisium (by Steveplays28)
Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Smarter Farmers (farmers replant) (by MehVahdJukaar)
spark (by Iucko)
Kotlin for Forge (by thedarkcolour)
Neko's Enchanted Books (by Nekomaster1000)
Game Menu Remove GFARB (by morimori0317)
CreativeCore (by CreativeMD)
Configured (by MrCrayfish)
Structure Gel API (by ModdingLegacy)
Inventory Sorter (by cpw)
Collective (by Serilum)
Just Enough Items (JEI) (by mezz)
BCLib (by Quiqueck)
Hourglass (by DuckyCrayfish)
Connectible Chains [FORGE] (by mysticpasta1)
playerAnimator (by KosmX)
Placebo (by Shadows_of_Fire)
Bookshelf (by DarkhaxDev)
Cupboard (by someaddon)
Blueprint (by TeamAbnormals)
Callable Horses (by Tschipp)
oωo (owo-lib) (by gliscowo)
Lionfish API (by mcl_ender)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Caelus API (Forge/NeoForge) (by TheIllusiveC4)
Sinytra Connector (by Su5eD)
TerraBlender (Forge) (by TheAdubbz)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Just Enough Breeding (JEBr) (by Christofmeg)
Weaker Spiderwebs (by Serilum)
YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
Particle Core (by fzzyhmstrs)
Kiwi 🥝 (NeoForge) (by Snownee)
Citadel (by sbom_xela)
AppleSkin (by squeek502)
Dungeons Enhanced (by Valarauko9)
HT's TreeChop (by hammertater)
Domestication Innovation (by sbom_xela)
Gardens of the Dead (by ochotonida)
Durability Tooltip (by SuperMartijn642)
Complementary Shaders - Unbound (by EminGT)
BetterEnd (by Quiqueck)
L_Ender 's Cataclysm (by mcl_ender)
YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
Neruina - Ticking Entity Fixer (by bawnorton)
Searchables (by Jaredlll08)
Cobweb (by CrystalSpider)
YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)
Just Enough Resources (JER) (by way2muchnoise)
Puzzles Lib [Forge & Fabric] (by Fuzs)
YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)
Fast Paintings (by MehVahdJukaar)
Hearths (by bebebea_loste)
Fabulous Foliage (by creepermax123)
Alternate Current (by SpaceWalkerRS)
Sound Physics Remastered (by henkelmax)
Fruitful Fun 🍊 (by Snownee)
GlitchCore (by TheAdubbz)
YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
Dynamic FPS (by juliand665)
Sawmill (by MehVahdJukaar)
Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
Traveler's Titles (Forge) (by YUNGNICKYOUNG)
Dragon Mounts: Legacy (by Kay9Unit)
Structure Essentials[Forge/Fabric] (by someaddon)
CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)
Konkrete [Forge/NeoForge] (by Keksuccino)
Diagonal Fences [Forge & Fabric] (by Fuzs)
Farmer's Delight (by vectorwing)
Serene Seasons (by TheAdubbz)
My Nether's Delight (by soytutta)
Oculus (by Asek3)
Uppers (by vadis365)
Jade 🔍 (by Snownee)
YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
Soul fire'd (by CrystalSpider)
Buzzier Bees (by TeamAbnormals)
Catalogue (by MrCrayfish)
Forgified Fabric API (by Su5eD)
Curios API (Forge/NeoForge) (by TheIllusiveC4)
GraveStone Mod (by henkelmax)
Immersive UI (by SSKirillSS)
FindMe (by Buuz135)
Small Ships [Fabric & Forge] (by talhanation)
[EMF] Entity Model Features [Fabric & Forge] (by traben_0)
Not Enough Recipe Book [NERB] (by SSKirillSS)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Cherished Worlds (Fabric/Forge/NeoForge/Quilt) (by TheIllusiveC4)
Sildur's Vibrant shaders (by Sildur)
Connector Extras (by Su5eD)
Formations (Structure Library) (by SuperMartijn642)
Embeddium++ (by SrRapero720)
Xaero's World Map (by xaero96)
Mouse Tweaks (by YaLTeR)
Controlling (by Jaredlll08)
Artifacts (by ochotonida)
GeckoLib (by Gecko)
Bliss Shaders (by Xonk___)
Villager Comfort Updated (by leahx_y2k)
No Chat Reports (by Aizistral)
Canary (by AbdElAziz333)
Sound​s (by IMB11)
fix GPU memory leak[Forge/Fabric] (by someaddon)
Alex's Caves (by sbom_xela)
Alex's Delight (by NCP_Bails)
Diagonal Walls (by Fuzs)
Complementary Shaders - Reimagined (by EminGT)
Stony Cliffs Are Cool (by bebebea_loste)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Amendments (by plantspookable)
Friends & Foes (Forge/NeoForge) (Copper Golem,Crab,Glare,Moobloom,Iceologer,Rascal,Tuff Golem,Wildfire,Illusioner) (by Faboslav)
Easy Magic [Forge & Fabric] (by Fuzs)
Lychee (Forge) (by Snownee)
Supplementaries (by MehVahdJukaar)
Xaero's Minimap (by xaero96)
xali's Bushy Leaves (by xalixilax)
Backpacked (by MrCrayfish)
FastSuite (by Shadows_of_Fire)
Sodium/Embeddium Dynamic Lights (by Txni)
Structory (by botanydev)
Framework (by MrCrayfish)
Visuality: Reforged (by DragonsPlus)
Boids
particular
shushi_bar
true ending

**Comment by RaptorMother** [comment]
Am going to add my own crash report to this too. It's not instantly when it rains for me, but rather, in a certain area of the world if I approach (as it's raining in that zone), the crash occurs immediately.

https://pastebin.com/aNeqEfiV

**Comment by swuff-star** [comment]
Unfortunately don't have a log on hand, but also have been experiencing this. It appears related to biomes that don't normally receive precipitation.

**Comment by Ryorama** [comment]
I've had this issues as well, after looking further into it([link](https://github.com/nonamecrackers2/simple-clouds/blob/571414f3d0ddb1c7d5f25f24c29680b78fb73075/src/main/java/dev/nonamecrackers2/simpleclouds/client/renderer/rain/PrecipitationQuad.java#L50)), if it can't determine the precipitation type of an area it will throw an error which will cause the game to crash. I brought it up in the Discord mentioning that there should be a better way to handle it and he confirmed my suspicions. As for when it'll be fixed, I'm not entirely sure

**Comment by nonamecrackers2** [comment]
Seems to be the same as #17. Fixing that should fix this issue.

> As for when it'll be fixed, I'm not entirely sure

Definitely next release, though it'll probably be a bit before that
