### ISSUE TITLE
[Bug]: Crash on launch with no other mods

### ISSUE THREAD

**Issue by Wartich** [nonamecrackers2/simple-clouds#7]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.6

### Graphics Card

NVIDIA GeForce GTX 1660

### Drivers Version

32.0.15.6590

### Describe the Bug

A bug happened! Yes! It did!

I added the simple clouds mod to my modpack, and it crashed on launch. At first i thought it's one of the optimization mods, so i removed all mods, but it still crashes for some reason. 

### Steps to Reproduce

1. Go to idk
2. Click on something
3. Make it work
4. See no error

### Crash Reports/Logs

[crash-2024-10-16_10.55.31-client.txt](https://github.com/user-attachments/files/17391563/crash-2024-10-16_10.55.31-client.txt)

### Mod List

Nada

**Comment by nonamecrackers2** [comment]
Can you also send your latest.log?

**Comment by Wartich** [comment]
A little update, it seems that some old mod config causes that. It crashes when they are still there, but when i clear the config folder out it works fine

**Comment by Wartich** [comment]
[latest.log](https://github.com/user-attachments/files/17406990/latest.log)


[17Oct2024 09:16:56.295] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to validate feature bounds for mods: [Bound[featureName=openGLVersion, featureBound=[4.3,), modInfo=net.minecraftforge.fml.loading.moddiscovery.ModInfo@41f35f7c]]

I believe this is an issue, some old mod config probably makes it use earlier openGL? even though my gpu is compatible with more modern ones
I'll try removing configs one by one to see which one causes that and report

**Comment by Wartich** [comment]
It seems that fml.toml was an issue, when i deleted it, everything started up without an issue even with all my mods from the modpack
[fml.txt](https://github.com/user-attachments/files/17407493/fml.txt)

**Comment by Wartich** [comment]
Not sure why though, defaultconfigs folder is empty and i don't see anything else that could affect it in the fml.toml

**Comment by nonamecrackers2** [comment]
> [latest.log](https://github.com/user-attachments/files/17406990/latest.log)
> 
> 
> 
> 
> 
> [17Oct2024 09:16:56.295] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to validate feature bounds for mods: [Bound[featureName=openGLVersion, featureBound=[4.3,), modInfo=net.minecraftforge.fml.loading.moddiscovery.ModInfo@41f35f7c]]

Simple Clouds adds this, though I'm not sure why it's having trouble with it

**Comment by nonamecrackers2** [comment]
Looks like something might not be working correctly with Forge. I'm not certain so I'll have to investigate this further

**Comment by Wartich** [comment]
Idk why are we texting eachother both here and on discord lol

**Comment by nonamecrackers2** [comment]
Eh either here or there works lol

**Comment by nonamecrackers2** [comment]
Should be fixed in the next major release
