### ISSUE TITLE
[Bug]: Compatibility Issue with Spice of Life Valheim

### ISSUE THREAD

**Issue by A4AAAAAA** [nonamecrackers2/simple-clouds#76]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

0.6.3

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Graphics Card

NVIDIA GTX 1060 

### Describe the Bug

Crash upon start up most likely because of an incompatibility with SOL Valheim both updated and non-updated.

### Steps to Reproduce

1.Download both SOL Valheim and Simple Clouds
2.Start MC
3.Crash

### Crash Reports/Logs

https://pastebin.com/RCsrPnfp

### Mod List

I have a modlist but the crash only occurs when both mods are installed and I have tried making a modpack only with the 2 mods but if it is needed I can reply to this with the mod list.

**Comment by nonamecrackers2** [comment]
Can you send your latest.log?

**Comment by A4AAAAAA** [comment]
it suddenly works, couldn't tell you why

**Comment by A4AAAAAA** [comment]
I now know why this happened. Something with Simple Clouds makes it alway be the reason why Minecraft crashes in the crash report even when it isn't the source of the problem. If I can help with identifying this issue I'd be very glad to do so.

**Comment by nonamecrackers2** [comment]
Yeah it’s really annoying and will be fixed in the next update
