### ISSUE TITLE
[Suggestion]: Weather2 Compatibility

### ISSUE THREAD

**Issue by TheCanadianCactus** [nonamecrackers2/simple-clouds#77]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

An option to disable its own cloud generation, and instead generate clouds based off of clouds from weather2

**Comment by llenderr** [comment]
That mode not possible to realistic

**Comment by hedkne43rei0pow** [comment]
why would this be helpful? they are both weather mods that add very similar things?

**Comment by VirtualGaming1** [comment]
The cloud system that Weather2 mod use is completely different and there is no way to get data from that mod anyway

**Comment by hedkne43rei0pow** [comment]
It would probably be more practical to make a simple clouds addon to adds similar things too weather2

**Comment by nonamecrackers2** [comment]
This wouldn't be very practical since Simple Clouds uses a completely different system, and trying to add compatibility in this way would require serious restructuring of the mod.
