### ISSUE TITLE
[Suggestion]: Configurable Cloud Height

### ISSUE THREAD

**Issue by Aiva418** [nonamecrackers2/simple-clouds#82]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

For some background, I decided to try and load up Simple Clouds just now with a modified version of Tectonic (I changed its internal datapack to make the world about 2000 blocks deep), and the resulting world had clouds cutting through the terrain around y=100.

I know this is an edge case most players are unlikely to ever encounter, and as such I expect this to be (very) low on the list of priorities. That being said, having the option to greatly offset the height at which all clouds begin would be a nice touch, especially for anyone who wants to use this mod in conjunction with datapacks that modify the elevation limits.

**Comment by TSEG6** [comment]
You can already do this with commands

**Comment by Aiva418** [comment]
Oh swick. I didn't see that anywhere on the mod page, so I didn't think to try it. Thanks!
