### ISSUE TITLE
[Suggestion]: Add Fabric Support Please 

### ISSUE THREAD

**Issue by Big1N** [nonamecrackers2/simple-clouds#86]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I know you said to not ask about this but please hear me out I love this mod and stuff but I wish it can be made for fabric in the future. Everyone would love to use it with sodium and other performance mods that are only on fabric. Fabric would make this mod run a lot more better and smoother for everyone aswell and easier to add new features. To be honest in my opinion no one really uses forge and it’s super old, slow and outdated. Thanks for making this mod though and wish you good luck on development.

**Comment by Infinitekaosv3** [comment]
when they mean dont ask about this, they mean **dont** ask, that means no "but" or " hear me out "

**Comment by DrMalpracticewastaken** [comment]
90% chance this is someone under 13

**Comment by Big1N** [comment]
I’m actually 22 and have my drivers license to prove it

> 90% chance this is someone under 13

**Comment by Big1N** [comment]
> when they mean dont ask about this, they mean **dont** ask, that means no "but" or " hear me out "

So you don’t like fabric?

**Comment by Infinitekaosv3** [comment]
> > when they mean dont ask about this, they mean **dont** ask, that means no "but" or " hear me out "
> 
> So you don’t like fabric?

sense when did i ever say i hated fabric??? I said they dont want people asking for fabric support

**Comment by Big1N** [comment]
> > > when they mean dont ask about this, they mean **dont** ask, that means no "but" or " hear me out "
> > 
> > 
> > So you don’t like fabric?
> 
> sense when did i ever say i hated fabric??? I said they dont want people asking for fabric support

I understand so I take it thats my answer and that they will never support fabric?

**Comment by VirtualGaming1** [comment]
@Big1N it even say in the Mod description about porting and say DO NOT ASK for Fabric Port

> Ports
> Simple Clouds is currently only available for Forge (1.20.1) and NeoForge (1.21+). Please don’t ask for a Fabric port or backports to older versions. Versions for newer versions of the game will come when they are ready.

**Comment by DrMalpracticewastaken** [comment]
> I’m actually 22 and have my drivers license to prove it
> 
> > 90% chance this is someone under 13

This is just sad the fact that you are 22 and act like this.

**Comment by Big1N** [comment]
I apologize if I offended anyone I was just curious if the developers would ever support fabric in the future. As soon as I get the answer I’ll close this post

**Comment by Big1N** [comment]
> > I’m actually 22 and have my drivers license to prove it
> > > 90% chance this is someone under 13
> 
> This is just sad the fact that you are 22 and act like this.

Sorry if I offended you

**Comment by Big1N** [comment]
> @Big1N it even say in the Mod description about porting and say DO NOT ASK for Fabric Port
> 
> > Ports
> > Simple Clouds is currently only available for Forge (1.20.1) and NeoForge (1.21+). Please don’t ask for a Fabric port or backports to older versions. Versions for newer versions of the game will come when they are ready.

So I take that as a no then the devs won’t support fabric in the future

**Comment by Luke7381** [comment]
> ### Guidelines
> * [x]  By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability
> 
> ### Description of feature request
> I know you said to not ask about this but please hear me out I love this mod and stuff but I wish it can be made for fabric in the future. Everyone would love to use it with sodium and other performance mods that are only on fabric. Fabric would make this mod run a lot more better and smoother for everyone aswell and easier to add new features. To be honest in my opinion no one really uses forge and it’s super old, slow and outdated. Thanks for making this mod though and wish you good luck on development.

Currently there is no plans for a fabric port, though i assume they might plan on doing so in the near future at some point.

Also what do you mean "no one really uses forge"? Lots of users still use forge (some using both fabric and forge). In fact im sure more people will use "forge" in the future due to the independent NeoForge being a thing.

**Comment by nonamecrackers2** [comment]
Fabric support may or may not come in the future. Arguing here will not solve anything. We are all mature and responsible people here
