### ISSUE TITLE
[Suggestion]: Config

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/simple-clouds#88]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A config where you can change what time-stamp the WS music should play and start at when the WS encounters you

**Comment by TaintedBlock** [comment]
Ah yes, the wither clouds will start playing a musical when you enter the vicinity

**Comment by Infinitekaosv3** [comment]
> Ah yes, the wither clouds will start playing a musical when you enter the vicinity
what..??
