### ISSUE TITLE
[Suggestion]: CurseForge version pls (I need this for my modpack on CF)

### ISSUE THREAD

**Issue by Mysticpasta1** [nonamecrackers2/simple-clouds#91]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Can you add this to the CF 3rd party list or on Curseforge itself, this way CF only modpack like mine can use it

**Comment by pinkygrocket** [comment]
[bro](https://www.curseforge.com/minecraft/mc-mods/simple-clouds)

**Comment by Mysticpasta1** [comment]
oh

**Comment by DrMalpracticewastaken** [comment]
💀

**Comment by VirtualGaming1** [comment]
feel like he did not even look on CF before he posted this -_- (Facepalm)
