### ISSUE TITLE
[Bug]: Game crashed on startup when Reforged formely Tiered is anlong side it.

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [nonamecrackers2/simple-clouds#97]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.21.1

### Mod Version

0.6.3

### Mod Loader

NeoForge

### Mod Loader Version

21.1.74

### Graphics Card

3060 12gb

### Drivers Version

566.03

### Describe the Bug

well the games crashed on startup when this mod is enabled alongside the reforged formerly tiered mod. removes your or the another mod fixes the issue. i dont know why and for me it doesnt make sense but i found it out after taking hours disabling one mod at a time. hope for a fix

### Steps to Reproduce

Launch Game and Crash at startup

### Crash Reports/Logs

-

### Mod List

to big i am currently making a modpack i try to get a log and a modlist later

**Comment by nonamecrackers2** [comment]
Please reopen this with a crash report and log file attached
